### ISSUE TITLE
Error on sample code LLaVA-v1.5(Simple Interactive Demos)

### ISSUE THREAD

**Issue by sentinel8b** [Q-Future/Q-Instruct#16]
I tried to run 'Simple Interactive Demos' on LLaVA-v1.5
I installed dependencies through 
```
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
pip install -e .
```
And I run the example code.
```python
from llava.mm_utils import get_model_name_from_path
from llava.eval.run_llava import eval_model
model_path = "teowu/llava_v1.5_7b_qinstruct_preview_v0.1" 
prompt = "Rate the quality of the image. Think step by step."
image_file = "fig/sausage.jpg"
args = type('Args', (), {
    "model_path": model_path,
    "model_base": None,
    "model_name": get_model_name_from_path(model_path),
    "query": prompt,
    "conv_mode": None,
    "image_file": image_file,
    "sep": ",",
})()
eval_model(args)
```

I got the result 
```
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
```
```
/root/anaconda3/envs/Qinstruct/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.  warnings.warn
Traceback (most recent call last):                                                                                                         
  File "/root/workplace/LLaVA/test_single_query.py", line 15, in <module>                                                                   
    eval_model(args)                                                                                                                        
  File "/root/workplace/LLaVA/llava/eval/run_llava.py", line 119, in eval_model                                                            
    do_sample=True if args.temperature > 0 else False,                                                                                     
AttributeError: 'Args' object has no attribute 'temperature'
```

**Comment by lexuszhi1990** [comment]
according to llava demo, change args to `type('Args', (), { "model_path": args.model_path, "model_base": None, "model_name": get_model_name_from_path(args.model_path), "query": prompt, "conv_mode": None, "image_file": image_file, "sep": ",", "temperature": 0,     "top_p": None, "num_beams": 1, "max_new_tokens": 512})()`

**Comment by sentinel8b** [comment]
Thanks it works well with new args.
